### ISSUE TITLE
Is it possible to avoid clearing the screen when starting an app ?

### ISSUE THREAD

**Issue by X-Ryl669** [canselcik/libremarkable#105]
Ideally, I'd like to pop up a calculator widget upon gesture recognition, so to avoid disrupting the current flow, I'd like to capture what's actually on the hardware framebuffer while starting the app, and use that as a background image. So, is it possible to:
1. Capture the hardware framebuffer before it's actually messed up by the application?
2. Start the application without flashing the screen (so it's not disturbing)?

**Comment by LinusCDE** [comment]
Hi,

I don't see a problem with this. The application should only draw over stuff it needs to.

If you just need a specific rectangular area, you don't need to clean the remaining framebuffer at all.

If you `use` the `libremarkable::framebuffer::FramebufferIO`-Trait [(Doc)](https://docs.rs/libremarkable/latest/libremarkable/framebuffer/trait.FramebufferIO.html), you have access to `read_pixel`, `write_pixel` as well as `dump_region` and `restore_region` if you feel more adventurous or need a way to easily restore the previous framebuffer when closing.

> 1. Capture the hardware framebuffer before it's actually messed up by the application?

Should be easy by doing a `dump_region()` of the entire framebuffer and a `restore_region()` later.

> 2. Start the application without flashing the screen (so it's not disturbing)?

You can use `partial_refresh` which is provided by the `libremarkable::framebuffer::FramebufferRefresh`-Trait [(Doc)](https://docs.rs/libremarkable/latest/libremarkable/framebuffer/trait.FramebufferRefresh.html). Most values are documented, but finding a kind of refresh that suits your app best with minimal delay is mostly going be feeling and trial & error imo.

Here are some examples, that use this method:
 - [Libremarkable Appctx](https://github.com/canselcik/libremarkable/blob/5b9316a/src/appctx.rs#L363-L375)
 - [Refresh in plato depending on quality level](https://github.com/LinusCDE/plato/blob/a6d3fa2/src/framebuffer/remarkable.rs#L170-L308)
 - [Most partial refreshes in my chess app](https://github.com/LinusCDE/chessmarkable/blob/f2360f3/src/bin/chessmarkable/canvas.rs#L36-L46) (reasonable time, with not too much ghosting on gray background)
 -  [Partial refresh in doomarkable](https://github.com/LinusCDE/doomarkable/blob/47ac96/src/main.rs#L251-L270) (as fluid as possible and depends on model)

On the rM 2, the [remarkable-framebuffer](https://github.com/ddvk/remarkable2-framebuffer) project is the shim that is used for all homebrew stuff. It fakes the framebuffer of the rM 1 and maps it to fewer ones. The mapping code can be found [here](https://github.com/ddvk/remarkable2-framebuffer/blob/10464b7/src/server/main.cpp#L44-L85).

### Aside regarding transparent images

If you need something that can leave gaps or want rounded shapes that preserve the background, you need to manually calculate new pixels and take the old ones into account. I had that problem already when making chessmarkable, so I added methods for that to my canvas helper class [here](https://github.com/LinusCDE/chessmarkable/blob/f2360f3/src/bin/chessmarkable/canvas.rs#L308-L378). Feel free to just use them as you can use those to overlay any transparent image over the existing framebuffer. I already did a bunch of performance testing on that, and using fixed digits instead of floats does not give any performance benefit as the fpu (called neon) seemingly is just that fast already. I used the `dump_region` there to reduce the needed read pixel operations though.

The [screenshot example](https://github.com/canselcik/libremarkable/blob/master/examples/screenshot.rs) might also prove useful as it also turns the framebuffer into an image (the srgb/gamma mapping is nice to have, but not needed to be functional).

**Comment by X-Ryl669** [comment]
Thanks a lot for your detailed answer!

**Comment by LinusCDE** [comment]
Since this has been answered, this issue is probably long overdue for closure. Feel free to ask follow-up questions if needed though.
