### ISSUE TITLE
Use with Qt

### ISSUE THREAD

**Issue by AdamSLevy** [canselcik/libremarkable#12]
Is it possible to use this library with Qt frameworks for building UIs

**Comment by Ameb** [comment]
You can already use Qt framework for building UIs, since the reMarkable ships with the libraries. Check this [example](https://github.com/reHackable/reHackable-HelloWorld), and if you are using Qt Creator [here](http://remarkablewiki.com/devel/qt_creator) is a guide.

This library allows you to control the framebuffer directly. For this to work in the tablet i think we would need a [QPA](http://wiki.qt.io/Qt_Platform_Abstraction) plugin implementation using libremarkable.

**Comment by canselcik** [comment]
As @Ameb pointed out, if you wanted to use Qt framework to build the UI and have it draw all UI elements on the framebuffer abstracted away by libremarkable, a Qt Platform Abstraction would be needed. You could also choose to use Qt framework to draw the UI elements and utilize libremarkable in your application to perform only the low latency drawing.

xochitl already comes with a QPA that's statically linked with it. It is not documented however by looking at the interface it provides, it looks like it would be similar to how one would use libremarkable.

Here is the interface for xochitl's

**Comment by AdamSLevy** [comment]
Thank you both so much for these replies and for your work on this library. I just got the remarkable tablet and see a ton of potential in the hardware but I am a little disappointed by the stock software.

It really is unfortunate that they didn't open source their software because no doubt the efforts made on this library could have also taken the existing software to new heights. 

I want to build better applications for the tablet. I have experience with Qt but from an example I saw elsewhere the refresh/response time using the Qt libs they provided is a little slower than their proprietary application, and even a small delay can affect usability and enjoyability. 

Am I correct that if a QPA was built around this library, that refresh rates could be improved?

Am I off base here? I'm brand new to rust and have limited experience reverse engineering binaries. However I understand the basic concepts.

**Comment by canselcik** [comment]
You're welcome. It's been a pleasure working on this platform: understanding and documenting it to create an alternative open implementation to which people from all over the world want to contribute is the reward on its own. :)
 
> Am I correct that if a QPA was built around this library, that refresh rates could be improved?

Yes, that is correct. When you use Qt without any such specific abstractions, it utilizes a one-size-fits all approach to drawing on the display/framebuffer, which doesn't yield great results on a display behind an [EPDC](https://wiki.mobileread.com/wiki/EPD_controller).

Slightly off tangent but theoretically you could even get X11 on the device (use `bitbake` to cross compile with all dependencies) and create a simple companion program in Rust with an infinite loop that just sends the framebuffer `MXCFB_SEND_UPDATE` with arguments to quick refresh the entire framebuffer. This would allow you to even be able to use a window manager with limited framerate.

I would recommend looking into the `libqsgepaper` interface if you want to create a QPA. You would probably end up creating a QPA wrapping around libremarkable and using its most essential features.

**Comment by LinusCDE** [comment]
You could technically do this with in combinations QT crates. Not sure how a custom epaper backend would look like though and whether it would have significant advantages to the default one contained in the toolchains.

For building current QT stuff, you need to make sure to use a current toolchain. Oecore will likely not run anymore due to outdated QT libs used in it. The most recent toolchain should always be [available here](https://remarkablewiki.com/devel/toolchain) and integration with rust will be similar to the examples with oecore.

**Comment by LoganDark** [comment]
I don't like Qt and don't think it would be useful here. libremarkable should not worry about supporting Qt.

**Comment by LinusCDE** [comment]
For now I think this won't be happening anytime soon. Feel free to ask follow-up questions. If things progress on this and someone is willing to try to add some kind of QT-Integration we can re-open this issue or make a new one.

I doubt this will be happening anytime soon though. So closing this for now.
