### ISSUE TITLE
weird artifacts

### ISSUE THREAD

**Issue by darvin** [canselcik/libremarkable#9]
Hello!
I'm using your library in my port of Plato ebook reader. 

https://github.com/darvin/plato

(thats the usage)
https://github.com/darvin/plato/blob/master/src/framebuffer/remarkable.rs

I see those artifacts:

![img_5080](https://user-images.githubusercontent.com/309302/40468426-41e9d484-5ee2-11e8-8d1d-ab761e065bfd.JPG)
![img_3836](https://user-images.githubusercontent.com/309302/40468430-44e85688-5ee2-11e8-8a91-daadbc95aeb4.JPG)

clearly, i misusing it somehow, got any tips?

Thank you for hard work making this library!

**Comment by canselcik** [comment]
Hi,

I am really impressed with what you've posted. Seeing work like this built upon this library and my findings justifies the time I spent on it so far, so thank you for that. :)

I have a few steps that you might take to diagnose the situation. Firstly, after you're done drawing, with the visual artifacts on the screen, could you try doing a partial refresh on the entire screen to see if the artifacts disappear? I would expect them to disappear since if they don't disappear, that will make it a very curious case.

Given these artifacts disappear after a partial refresh on the entire screen, you might be experiencing [this](https://github.com/canselcik/libremarkable/blob/master/src/framebuffer/mod.rs#L141-L158):
```
    ///    1) PxP must process 8x8 pixel blocks, and all pixels in each block
    ///    are considered for auto-waveform mode selection. If the
    ///    update region is not 8x8 aligned, additional unwanted pixels
    ///    will be considered in auto-waveform mode selection.
    ///
    ///    2) PxP input must be 32-bit aligned, so any update
    ///    address not 32-bit aligned must be shifted to meet the
    ///    32-bit alignment.  The PxP will thus end up processing pixels
    ///    outside of the update region to satisfy this alignment restriction,
    ///    which can affect auto-waveform mode selection.
    ///
    ///    3) If input fails 32-bit alignment, and the resulting expansion
    ///    of the processed region would add at least 8 pixels more per
    ///    line than the original update line width, the EPDC would
    ///    cause screen artifacts by incorrectly handling the 8+ pixels
    ///    at the end of each line. 
```

In that case, you might benefit from calling `Framebuffer::set_min_update_dimension(..)` from the `Framebuffer::FramebufferRefresh` trait found [here](https://github.com/canselcik/libremarkable/blob/master/src/framebuffer/mod.rs#L110-L117).
```
    /// The minimum height/width that we will enforce before each call to MXCFB_SEND_UPDATE
    /// The higher it is, the more likely we are to have collisions between updates.
    /// The smaller it is, the more likely we are to have display artifacts.
    /// 16 or 32 also seems like a decent minimum as this accelerates the initial processing,
    /// and therefore minimizing collisions through a different mechanism.
    ///
    /// This value defaults to 16 and is a global `AtomicUsize`.
    fn set_min_update_dimension(&mut self, pixels: usize);
```
Let me know if you get improved results with this. In either scenario, we can continue brainstorming.

**Comment by sandsmark** [comment]
they don't look like any waveform/update artifacts I've seen, so my guess would be rendering errors. try dumping the entire framebuffer to an image file and inspecting it locally?

and I haven't had time to learn rust yet, unfortunately, but your set_pixel() function looks weird, you pass `color` as alpha as well? I'd assume alpha would be 255 by default.

**Comment by mseri** [comment]
@darvi can you add the issue page on the plato fork repository. I was going to point out that for float comparsion, as you do in 'set_blended_pixel`, for example, equality is rarely the right comparison and it would be better to use something like `float_cmp`: https://mikedilger.github.io/float-cmp/float_cmp/index.html

**Comment by canselcik** [comment]
Unrelated to this issue as a whole but relating my comment earlier: I wanted to clarify that `set_min_update_dimension` was a workaround I had in place that we no longer need thanks to @SafariMonkey's fix.

Since that fix, I've removed the `set_min_update_dimension` and the `min_update_dimension` workaround as a whole. Therefore as @sandsmark pointed out, this sounds like something might be going wrong in the color space conversion, specifically pertaining the alpha channel. I also wouldn't be extremely surprised if my color conversion code is contributing to the situation.

Do you see these artifacts in `/tmp/frame.jpg` when you do the following (given you have the device on 10.11.99.1)?
```
ssh root@10.11.99.1 "cat /dev/fb0" | \
  ffmpeg -vcodec rawvideo \ 
         -f rawvideo \
         -pix_fmt gray16le \
         -s 1408,1872 \
         -i - \
         -vframes 1 
         -f image2
         -vcodec mjpeg /tmp/frame.jpg
```

**Comment by darvin** [comment]
@mseri  added issue page

**Comment by darvin** [comment]
@canselcik im doing something very wrong::

![frame4](https://user-images.githubusercontent.com/309302/41196393-ec78b65e-6bf3-11e8-9fc5-32a92a064428.jpg)

**Comment by darvin** [comment]
so thats what ffmpeg returns. means its not about waveform update, its about color conversion/pixel format aryphmetics!

**Comment by darvin** [comment]
Ive tried to use only BLACK color or GRAY(29) for drawing:

![blackonly](https://user-images.githubusercontent.com/309302/41196441-24581b68-6bf5-11e8-8a31-7f8ca1f8cbdd.jpg)
![blackonly2](https://user-images.githubusercontent.com/309302/41196442-2472c7ba-6bf5-11e8-9a22-f12175469596.jpg)
![grayonly](https://user-images.githubusercontent.com/309302/41196443-24898586-6bf5-11e8-9f59-0bc6c0a68103.jpg)

**Comment by darvin** [comment]
My problem clearly is down to this function that is used for setting blended pixel:

```
    fn set_blended_pixel(&mut self, x: u32, y: u32, color: u8, alpha: f32) {
        if alpha == 1.0 {
            self.set_pixel(x, y, color);
            return;
        }
        let dst_color = self.fb.read_pixel(y as usize, x as usize);
        let dst_color = dst_color.as_native();
        let (dst_r, dst_g, dst_b) = (dst_color[0], dst_color[1], dst_color[2]);
        let src_alpha = color as f32 * alpha;
        let r = src_alpha + (1.0 - alpha) * dst_r as f32;
        let g = src_alpha + (1.0 - alpha) * dst_g as f32;
        let b = src_alpha + (1.0 - alpha) * dst_b as f32;
        let a = (r+g+b)/3.0;
        self.fb.write_pixel(y as usize, x as usize, color::NATIVE_COMPONENTS(r as u8, b as u8, g as u8, a as u8));
    }
```

**Comment by darvin** [comment]
fixed it!

**Comment by mseri** [comment]
Thanks! How did you fix it in the end?

**Comment by darvin** [comment]
@mseri i ignored alpha:

```rust

    fn set_blended_pixel(&mut self, x: u32, y: u32, color: u8, alpha: f32) {
        if alpha == 1.0 {
            self.set_pixel(x, y, color);
            return;
        }
        let rgb = self.fb.read_pixel(y as usize, x as usize).as_native();
        let color_alpha = color as f32 * alpha;
        let r = color_alpha + (1.0 - alpha) * rgb[0] as f32;
        let g = color_alpha + (1.0 - alpha) * rgb[1] as f32;
        let b = color_alpha + (1.0 - alpha) * rgb[2] as f32;
        self.fb.write_pixel(y as usize, x as usize, color::NATIVE_COMPONENTS(r as u8, g as u8, b as u8, 255));
    }
```


it maybe wrong but it looks much nicer now, no artifacts (although maybe there is no blending either but it looks alright)

**Comment by canselcik** [comment]
@darvin Glad to hear that the issue is resolved. The ability to dump the framebuffer and visually inspect it seems to have definitely helped narrow down the problem's source.

From your code above, to me it looks like you haven't lost blending at all since you are multiplying each component with `(1.0 - alpha)` before writing the pixel.

On a side note, here are some values I collected from tracing `xochitl` and from the `mxc_epdc_fb_test` program that FreeScale Semiconductor has created to demo/test the EPDC ([relevant section](https://github.com/canselcik/libremarkable/blob/master/reference-material/mxc_epdc_fb_test.c#L369-L393)):
```rust
            &color::BLACK => [0x00, 0x00, 0x00, 0x00],
            &color::RED => [0xF8, 0x00, 0xF8, 0x00],
            &color::GREEN => [0x07, 0xE0, 0x07, 0xE0],
            &color::BLUE => [0x00, 0x1F, 0x00, 0x1F],
            &color::WHITE => [0xFF, 0xFF, 0xFF, 0xFF],
```
```c
static void draw_rgb_color_squares(struct fb_var_screeninfo * var)
{
	int i, j;
	int *fbp = (int *)fb;

	/* Draw red square */
	for (i = 50; i < 250; i++)
		for (j = 50; j < 250; j += 2)
			fbp[(i*var->xres_virtual+j)*2/4] = 0xF800F800;

	/* Draw green square */
	for (i = 50; i < 250; i++)
		for (j = 350; j < 550; j += 2)
			fbp[(i*var->xres_virtual+j)*2/4] = 0x07E007E0;

	/* Draw blue square */
	for (i = 350; i < 550; i++)
		for (j = 50; j < 250; j += 2)
			fbp[(i*var->xres_virtual+j)*2/4] = 0x001F001F;

	/* Draw black square */
	for (i = 350; i < 550; i++)
		for (j = 350; j < 550; j += 2)
			fbp[(i*var->xres_virtual+j)*2/4] = 0x00000000;
}
```

**Comment by canselcik** [comment]
@darvin You might be interested in building against the latest version of the library that I published yesterday as they contain non-trivial improvements to `common::color` mainly taking care of the `rgb -> common::color` conversion. This also came with an unexpected speedup and I expect it might take care of some of the remaining artifacts you have.

The way that the color code is now structured makes a lot more sense than how it used to be: to put it in terms that the `image` crate would put it, we are now treating the framebuffer as an `ImageBuffer<LumaA<u8>, Vec<u8>>` meaning it is a contiguous `u8` buffer where each pixel is represented by 2 `u8`, one for the `luma`, one for the `alpha`, which allows you to write `rgb565_le` into it and have it display the pixel at the expected shade of gray as that nicely maps into a sensible `LumaA` value.

**Comment by canselcik** [comment]
As of this commit, I think it is fair to say the color space issues should be resolved: https://github.com/canselcik/libremarkable/commit/61e0881da250f515b7a0b6dff666383069c485e6

Here is what my test involves -- notice dumping the framebuffer as RGB565_le and passing it through ffmpeg on the computer shows the retained color data. The framebuffer is simply rgb565.

![ColorTest0](https://i.imgur.com/udp5SON.jpg)
